# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, unique=True)),
                ('hostname', models.CharField(max_length=64)),
                ('num_cpu', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=32)),
                ('num_memory', models.CharField(max_length=32)),
                ('memory', models.CharField(max_length=64)),
                ('sysversion', models.CharField(max_length=32)),
            ],
        ),
    ]
